manual_task:
  trigger_type: manual
  auto_cancellation: $CIRRUS_BRANCH !=~ 'release/.*'
  allow_failures: $CIRRUS_BRANCH !=~ 'release/.*'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  test_script: echo "Hello World from macOS! (manual trigger)"

commit_task:
  alias: commit
  only_if: ${CIRRUS_CHANGE_IN_REPO} != ${CIRRUS_LAST_GREEN_CHANGE}
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  
  commit_script: echo "Hello World from macOS! (commit push)"
  
  test_script: echo ${CIRRUS_BRANCH} - ${CIRRUS_TAG} - ${CIRRUS_PR} - ${CIRRUS_LAST_GREEN_BUILD_ID} - ${CIRRUS_BASE_SHA} - ${CIRRUS_BUILD_ID}

dep_task:
  only_if: ${CIRRUS_CHANGE_IN_REPO} != ${CIRRUS_LAST_GREEN_CHANGE}
  depends_on: commit
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  test_script: echo "depedent task"

tag_task:
  only_if: $CIRRUS_TAG != ""
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  tag_script: echo "Hello World from macOS! (tag push)"

  test_script: echo ${CIRRUS_BRANCH} - ${CIRRUS_TAG} - ${CIRRUS_PR} - ${CIRRUS_LAST_GREEN_BUILD_ID} - ${CIRRUS_BASE_SHA} - ${CIRRUS_BUILD_ID}

pr_task:
  only_if: $CIRRUS_PR != ""
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  pr_script: echo "Hello World from macOS! (PR push)"

  test_script: echo ${CIRRUS_BRANCH} - ${CIRRUS_TAG} - ${CIRRUS_PR} - ${CIRRUS_LAST_GREEN_BUILD_ID} - ${CIRRUS_BASE_SHA} - ${CIRRUS_BUILD_ID}
