commit_task:
  only_if: $CIRRUS_TAG == "" && $CIRRUS_PR == ""
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  
  commit_script: echo "Hello World from macOS! (commit push)"

tag_task:
  only_if: $CIRRUS_TAG != ""
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  tag_script: echo "Hello World from macOS! (tag push)"

pr_task:
  only_if: $CIRRUS_PR != ""
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  pr_script: echo "Hello World from macOS! (PR push)"
