commit_task:
  only_if: changesInclude('**')
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  
  commit_script: echo "Hello World from macOS! (commit push)"
  
  test_script: echo ${CIRRUS_BRANCH} - ${CIRRUS_TAG} - ${CIRRUS_PR} - ${CIRRUS_LAST_GREEN_BUILD_ID} - ${CIRRUS_BASE_SHA} - ${CIRRUS_BUILD_ID}

tag_task:
  only_if: $CIRRUS_TAG != ""
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  tag_script: echo "Hello World from macOS! (tag push)"

  test_script: echo ${CIRRUS_BRANCH} - ${CIRRUS_TAG} - ${CIRRUS_PR} - ${CIRRUS_LAST_GREEN_BUILD_ID} - ${CIRRUS_BASE_SHA} - ${CIRRUS_BUILD_ID}

pr_task:
  only_if: $CIRRUS_PR != ""
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  pr_script: echo "Hello World from macOS! (PR push)"

  test_script: echo ${CIRRUS_BRANCH} - ${CIRRUS_TAG} - ${CIRRUS_PR} - ${CIRRUS_LAST_GREEN_BUILD_ID} - ${CIRRUS_BASE_SHA} - ${CIRRUS_BUILD_ID}
