name: test2
run-name: ${{ github.sha }}
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-20.04
    environment:
      name: test
      url: https://test.pypi.org/project/dmri-amico/
    steps:
      - name: Download 
        uses: dawidd6/action-download-artifact@v2.26.0
        with:
          workflow: test.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          name: testfile
          path: dist
          search_artifacts: true

      - name: Check files
        run: |
          ls -l
          ls -l dist/*

      - name: Check pre-release
        if: github.event.release.prerelease == true && contains(github.event.release.tag_name, 'rc')
        run: |
          echo PRERELEASE

      - name: Check release
        if: github.event.release.prerelease == false
        run: |
          echo RELEASE
          echo ${{ github.event.release.tag_name }}
