name: test2
run-name: ${{ github.sha }}
on:
  release:
    types: [published, edited]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Download 
        uses: dawidd6/action-download-artifact@v2.26.0
        with:
          workflow: test.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          branch: main
          name: testfile
          path: dist
          search_artifacts: true

      - name: Check files
        run: |
          ls -l
          ls -l dist/*

      - name: Check release
        run: |
          echo ${{ github.event.release.tag_name }}
