name: Compile OpenBLAS on MacOS arm64
run-name: Compile OpenBLAS on MacOS arm64 - ${{ github.sha }}
on: workflow_dispatch
jobs:
  compile_openblas:
    strategy:
      matrix:
        arch:
          - [x86_64, ARMV8]
    name: ${{ matrix.arch[0] }}
    runs-on: macos-13
    steps:
      - name: Compile OpenBLAS
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        run: |
          curl -L -o OpenBLAS-0.3.24.tar.gz https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.24/OpenBLAS-0.3.24.tar.gz
          tar -xzf OpenBLAS-0.3.24.tar.gz
          sudo ln -fs /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          make -C OpenBLAS-0.3.24 TARGET=${{ matrix.arch[1] }} DYNAMIC_ARCH=1
          make install -C OpenBLAS-0.3.24 PREFIX=${GITHUB_WORKSPACE}/OpenBLAS

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: OpenBLAS_macos_${{ matrix.arch[0] }}
          path: ./OpenBLAS
          if-no-files-found: error
