name: test2
on:
  release:
    types: [published, edited]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Download 
        uses: dawidd6/action-download-artifact@v2.26.0
        with:
          workflow: test.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          name: test.txt
          path: dist
          search_artifacts: true

      - name: Check
        run: ls -l
