name: test2
on:
  release:
    types: [published, edited]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: wait
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Publish on PyPI'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusion: success
