name: test
run-name: ${{ github.sha }}
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: touch test.txt

      - name: Sleep 1min
        run: sleep 60

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: testfile
          path: ./test.txt
          if-no-files-found: error
